FROM pypy:3.9

WORKDIR /usr/src/app

RUN touch database.sqlite3
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "gunicorn", "-w 4", "-b", "0.0.0.0:8000", "app:create_app()"]